### ISSUE TITLE
Check for memory leaks / leaky goroutines

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#112]
Introduce some automation to check for memory leaks / leaky goroutines in UDS CLI

Couple of suggested tools:
 - https://github.com/uber-go/goleak
 - https://github.com/fortytw2/leaktest

**Comment by mikevanhemert** [comment]
Additional potential location for a [leaky goroutine](https://medium.com/codezillas/golang-leaky-goroutines-and-how-to-clean-them-30b505417028) in the CLI

**Comment by mikevanhemert** [comment]
Recommend closing this issue based on @UncleGedd's discussion with @Racer159 that UDS CLI goroutine use is not, in fact, leaky
