### ISSUE TITLE
Deploy time flag for architecture

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-cli#135]
This may be a weird edge case, but I am developing and deploying on an arm mac. I use [Colima](https://github.com/abiosoft/colima) for my docker socket and run a k3d cluster on top of this. The cluster has emulation support to run both arm and amd64 images, but uds-cli will detect the cluster as an arm cluster and prevent me from deploying an amd64 bundle.

The ideal solution I would like is to be able to deploy amd64 packages to an arm cluster. Zarf currently allows this through the `-a arm64` deploy time flag. If uds-cli were to expose this same flag, or a different way to bypass the cluster architecture check, this would allow me to deploy amd64 bundles onto my emulated magic cluster.

**Comment by UncleGedd** [comment]
https://github.com/defenseunicorns/uds-cli/pull/131
