### ISSUE TITLE
Enforce conventional commits

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#144]
IAW new guidelines and to get that sweet, sweet release note automation, enforce conventional commits for UDS CLI

Ref: https://github.com/defenseunicorns/kubernetes-fluent-client

**Comment by zachariahmiller** [comment]
I just put in a PR to uds-core for this same thing. If you'd like i can put one in here @UncleGedd. Just LMK

**Comment by UncleGedd** [comment]
please do!
