### ISSUE TITLE
Add Issue and PR Templates for uds-cli repo.

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#152]
Title is self explanatory. This would be nice. For reference: 

https://github.com/defenseunicorns/uds-template-capability/blob/main/.github/pull_request_template.md
https://github.com/defenseunicorns/uds-template-capability/tree/main/.github/ISSUE_TEMPLATE

I can open a PR if you'd like using the above as a baseline. @UncleGedd lmk!

**Comment by UncleGedd** [comment]
yes please!
