### ISSUE TITLE
Consistent Case Usage in YAML Schemas

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/uds-cli#194]
### Is your feature request related to a problem? Please describe

UDS CLI's bundle.yaml and config.yaml schemas include kebab-case or dash-case, but other Defense Unicorns projects use camelCase. Recommend aligning to one style

### Describe the solution you'd like

All yaml schema definitions follow the same look / feel as other Defense Unicorns projects.

**Comment by UncleGedd** [comment]
doneskies https://github.com/defenseunicorns/uds-cli/pull/387
