### ISSUE TITLE
Renovate Dashboard 🤖

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#229]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Edited/Blocked

These updates have been manually edited so Renovate will no longer make changes. To discard all commits and start over, click on a checkbox.

 - [ ] chore(deps): update dependency go to v1.21.6
 - [ ] fix(deps): update module github.com/pterm/pterm to v0.12.74

## Ignored or Blocked

These are blocked by an existing closed PR and will not be recreated unless you click a checkbox below.

 - [ ] [chore(deps): update helm release podinfo to v6.5.4](../pull/319)

## Detected dependencies

<details><summary>github-actions</summary>
<blockquote>

<details><summary>.github/actions/golang/action.yaml</summary>

 - `actions/setup-go v5.0.0@0c52d547c9bc32b1aa3301fd7a9cb496313a4491`

</details>

<details><summary>.github/actions/install-tools/action.yaml</summary>

 - `sigstore/cosign-installer v3.3.0@9614fae9e5c5eddabb09f90a270fcb487c9f7149`
 - `anchore/sbom-action v0.15.3@c7f031d9249a826a082ea14c79d3b686a51d485a`
 - `docker/setup-buildx-action v3.0.0@f95db51fddba0c2d1ec667646a06c2ce06100226`

</details>

<details><summary>.github/actions/save-logs/action.yaml</summary>

 - `actions/upload-artifact v4.1.0@1eb3cb2b3e0f29609092a73eb033bb759a334595`

</details>

<details><summary>.github/actions/zarf/action.yaml</summary>

</details>

<details><summary>.github/workflows/commitlint.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `actions/setup-node v4.0.1@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8`

</details>

<details><summary>.github/workflows/release.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `actions/upload-artifact v4.1.0@1eb3cb2b3e0f29609092a73eb033bb759a334595`
 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `actions/download-artifact v4.1.1@6b208ae046db98c579e8a3aa621ab581ff575935`
 - `docker/login-action v3.0.0@343f7c4344506bcbf9b4de18042ae17996df046d`
 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `actions/download-artifact v4.1.1@6b208ae046db98c579e8a3aa621ab581ff575935`
 - `goreleaser/goreleaser-action v5.0.0@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8`

</details>

<details><summary>.github/workflows/scan-codeql.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `github/codeql-action v3.23.0@e5f05b81d5b6ff8cfa111c80c22c5fd02a384118`
 - `github/codeql-action v3.23.0@e5f05b81d5b6ff8cfa111c80c22c5fd02a384118`

</details>

<details><summary>.github/workflows/scan-lint.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `pre-commit/action c7d159c2092cbfaab7352e2d8211ab536aa2267c`
 - `morphy/revive-action v2@sha256:dad5d9525a11d42ea2a36237f6a4082aef3db37cbd280eabf5e7b87eb033d0d4`

</details>

<details><summary>.github/workflows/scorecard.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `ossf/scorecard-action v2.3.1@0864cf19026789058feabb7e87baa5f140aac736`
 - `actions/upload-artifact v4.1.0@1eb3cb2b3e0f29609092a73eb033bb759a334595`
 - `github/codeql-action v3.23.0@e5f05b81d5b6ff8cfa111c80c22c5fd02a384118`

</details>

<details><summary>.github/workflows/test-e2e.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`
 - `docker/login-action v3.0.0@343f7c4344506bcbf9b4de18042ae17996df046d`

</details>

<details><summary>.github/workflows/test-schema.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`

</details>

<details><summary>.github/workflows/test-unit.yaml</summary>

 - `actions/checkout v4.1.1@b4ffde65f46336ab88eb53be808477a3936bae11`

</details>

</blockquote>
</details>

<details><summary>gomod</summary>
<blockquote>

<details><summary>go.mod</summary>

 - `go 1.21.5`
 - `github.com/AlecAivazis/survey/v2 v2.3.7`
 - `github.com/alecthomas/jsonschema v0.0.0-20220216202328-9eeeec9d044b@9eeeec9d044b`
 - `github.com/defenseunicorns/zarf v0.32.1`
 - `github.com/goccy/go-yaml v1.11.2`
 - `github.com/mholt/archiver/v3 v3.5.1`
 - `github.com/mholt/archiver/v4 v4.0.0-alpha.8`
 - `github.com/opencontainers/image-spec v1.1.0-rc5`
 - `github.com/pterm/pterm v0.12.72`
 - `github.com/spf13/cobra v1.8.0`
 - `github.com/spf13/viper v1.18.2`
 - `github.com/stretchr/testify v1.8.4`
 - `golang.org/x/exp v0.0.0-20240112132812-db7319d0e0e3@db7319d0e0e3`
 - `golang.org/x/mod v0.14.0`
 - `golang.org/x/sync v0.6.0`
 - `helm.sh/helm/v3 v3.13.3`
 - `oras.land/oras-go/v2 v2.3.1`

</details>

</blockquote>
</details>

<details><summary>helmv3</summary>
<blockquote>

<details><summary>src/test/packages/helm/unicorn-podinfo/Chart.yaml</summary>

 - `podinfo 6.5.3`

</details>

</blockquote>
</details>

<details><summary>regex</summary>
<blockquote>

<details><summary>.github/actions/zarf/action.yaml</summary>

 - `defenseunicorns/zarf v0.32.1`

</details>

<details><summary>src/test/bundles/04-init/uds-bundle.yaml</summary>

 - `defenseunicorns/zarf v0.32.1`
 - `defenseunicorns/zarf v0.32.1`

</details>

<details><summary>.github/actions/zarf/action.yaml</summary>

 - `defenseunicorns/zarf v0.32.1`

</details>

<details><summary>src/test/bundles/04-init/uds-bundle.yaml</summary>

 - `defenseunicorns/zarf v0.32.1`
 - `defenseunicorns/zarf v0.32.1`

</details>

</blockquote>
</details>

**Comment by catsby** [comment]
Both items in the "Edited/Blocked" list above are done, I'm going to close this old issue
