### ISSUE TITLE
More/better progress indicators

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#28]
There are a few places during bundle create and deploy that uds-cli is doing something but isn't showing any form of working or progress during said operation, this can be concerning to end users, and is especially bad with large bundles/slow hardware.

**Comment by UncleGedd** [comment]
@corang we've added some recent TUI enhancements including your PR and [this one](https://github.com/defenseunicorns/uds-cli/pull/97). Are there any other missing progress indicates your noticed?
