### ISSUE TITLE
Zarf v0.32 break UDS CLI (oci change)

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/uds-cli#296]
In [v0.32](https://github.com/defenseunicorns/zarf/releases/tag/v0.32.0) the OCI refs have changed and no longer publish with the arch in the tag. Need to update the UDS CLI lib to support this (better) publishing strategy.

<img width="458" alt="Screenshot 2024-01-01 at 5 29 56 PM" src="https://github.com/defenseunicorns/uds-cli/assets/882485/2cba8bf0-befe-44a8-ad24-b7b51c4e6b99">
<img width="824" alt="Screenshot 2024-01-01 at 5 29 51 PM" src="https://github.com/defenseunicorns/uds-cli/assets/882485/0fe71f4f-060d-4b51-8198-b51a93e052b1">

**Comment by decleaver** [comment]
updates in https://github.com/defenseunicorns/uds-cli/pull/300
