### ISSUE TITLE
Allow included task files to be callable from parent task files.

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-cli#325]
### Is your feature request related to a problem? Please describe

When leveraging `includes:` there is a common pattern emerging where the parent task file includes tasks that are basically duplicates of child tasks, but must exist because child tasks are not directly callable.  

See: https://github.com/defenseunicorns/uds-core/blob/main/tasks.yaml#L23-L49

Supporting the ability to call child tasks that were included with `includes:` directly from the parent task would reduce the need to duplicate the tasks at the top level.  

I think replicating the `internal` flag that exists in [go-task includes](https://taskfile.dev/api/#include) to indicate that they should not be callable from the parent seems like a pattern worth emulating.

### Describe the solution you'd like

- **Given**: a `task.yaml`:
```yaml
includes:
  - setup: ./tasks/setup.yaml
``` 
- **When** `uds run setup:k3d-test-cluster` 
- **Then** The `k3d-test-cluster` from `setup.yaml` would be run.

### Additional context

I also think updating `uds run --list` to support listing exposed child tasks would alleviate issues of not being able to quickly see what tasks are available which I suspect was previously being done with something like `cat tasks.yaml`.

**Comment by UncleGedd** [comment]
Thanks for this issue, thinking through all the options. Today, if you wanted to call a child task you'd have to specify the child `tasks.yaml` file using `-f`. So something like `uds run -f ./tasks/create.yaml child-task`. If you use that syntax, there's no need to include those duplicated child tasks in the parent `tasks.yaml`. Thoughts?

**Comment by rjferguson21** [comment]
The deficiency with that option is that is not discoverable without catting the parent tasks.yaml to find the referenced children's path and there is no way to codify which tasks are intended to be called directly.

Ideally you'd want someone with no knowledge of the repo to be able to see which actions are available (and intended) for them with just the uds-cli.

**Comment by UncleGedd** [comment]
Makes sense! We've got a a number of buns in the oven atm so it's difficult to judge priority for this but we would happily accept a PR

**Comment by decleaver** [comment]
related to https://github.com/defenseunicorns/uds-cli/issues/441#issue-2144834614 (plus list all)
