### ISSUE TITLE
Have some way to import variables from a file and use in tasks

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/uds-cli#338]
### Is your feature request related to a problem? Please describe

You should be able to pass in environment files somehow from task to task in a non-cumbersome manner. Coming from using make, I have a pattern that uses `include .env`, this sets environment variables for the rest of the targets. You should be able to source a file from the uds runner and have those variables work in the tasks.

Whether that's from a `variables:` block or via the uds-config.yaml file, that's fine.
Also, this doesn't really seem to do anything?

```bash
variables:
  - name: ENV_VAR_FILE
    default: .env
    type: file
```

### Describe alternatives you've considered

cat .env manually and for each variable do a separate action with `setVariables` to have my variables persist to other tasks

A workaround for now is to have to source that file in every single action that needs them

**Comment by UncleGedd** [comment]
Relates to #339

**Comment by decleaver** [comment]
Hello Mr. Cool (@zack-is-cool), so you should be able to accomplish this now by using the `envPath` [key](https://github.com/defenseunicorns/uds-cli/blob/main/docs/runner.md#environment-variables) in the task.
