### ISSUE TITLE
ToBundle Functions should take advantage of Zarf's `layout`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-cli#343]
### Describe what should be investigated or refactored

`ToBundle` should take advantage of Zarf's `layout` helpers to get the digests and paths it needs for a given package rather than filepath.Walking.

### Links to any relevant code

https://github.com/defenseunicorns/uds-cli/blob/edf67623f7513cddfb010340e399bacc9bfb5fd8/src/pkg/bundler/tarball.go#L114

### Additional context

The current code will actually break on Windows as written since it will get a relative path that does not contain forward slashes:  https://github.com/defenseunicorns/uds-cli/blob/edf67623f7513cddfb010340e399bacc9bfb5fd8/src/pkg/bundler/tarball.go#L132

**Comment by UncleGedd** [comment]
Updating the location of code to be refactored: https://github.com/defenseunicorns/uds-cli/blob/db61652fdd299d7d193732a0c6181102e495ab44/src/pkg/bundler/fetcher/local.go#L146

**Comment by UncleGedd** [comment]
closed with https://github.com/defenseunicorns/uds-cli/pull/622
