### ISSUE TITLE
Ensure `uds zarf tools` have versions

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#357]
Tracking this Zarf PR: https://github.com/defenseunicorns/zarf/pull/2232

Ensure we pull these change into UDS CLI

**Comment by decleaver** [comment]
` uds zarf tools helm version` produces the following:

 NOTE  Using config file

 NOTE  Using config file
helm 
` zarf tools helm version` produces:
helm v3.14.2

**Comment by decleaver** [comment]
Thanks for handling this one @TristanHoladay !
