### ISSUE TITLE
Support linting of Zarf packages

### ISSUE THREAD

**Issue by gscallon** [defenseunicorns/uds-cli#359]
### Is your feature request related to a problem? Please describe

I am attempting to lint the Zarf package in a UDS task runner workflow. I am receiving the following error:

```
gavinscallon@Gavins-MacBook-Pro-2 uds-runner-pipeline-python-hello-world % uds zarf dev lint -f zarf.schema.json

 NOTE  Saving log file to
       /var/folders/37/qqg82c0x2hx43pczwp305f0r0000gn/T/zarf-2024-01-25-16-23-05-1549175322.log
     ERROR:  open zarf.schema.json: file does not exist
```

The schema file appears to get compiled with the Zarf binary when used with the standalone Zarf binary. The linting is successful if we run `zarf dev lint`.

### Describe the solution you'd like

- **Given** a Zarf.yaml file exists
- **When** I go to run `uds zarf dev lint` 
- **Then** I am able to lint the Zarf package

### Describe alternatives you've considered

(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by Racer159** [comment]
Planning to pick this one up - since the zarf schema is in the repo now just gonna pick that up (let me know if a different path is desired)
