### ISSUE TITLE
Ensure Architecture setting precedence

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#360]
There are several ways to set a bundle's architecture. Ensure, document and test the following architecture option precedence

1. `-a` flag
2. `UDS_ARCHITECTURE` env var
3. `options.architecture` in `uds-config.yaml`
4. `metadata.architecture` in `uds-bundle.yaml`

**Comment by TristanHoladay** [comment]
confirmed architecture can be set by all methods and the above precedence holds.
