### ISSUE TITLE
Create pre-install (pre-flight) test to confirm version of Kubernetes matches supported versions

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-cli#4]
pre-flight test should check (at least) these few things:
* system has a kubecontext set
* k8s cluster is healthy per `kubectl get --raw='/readyz?verbose'`
* appropriate k8s version
* zarf init was completed (with git-server component)
* known misconfigurations

**Comment by noahpb** [comment]
Should this be added to dubbd, I added a few more checks to the existing `preflight.sh` script in https://github.com/defenseunicorns/uds-package-dubbd/pull/517

**Comment by noahpb** [comment]
added in [#517](https://github.com/defenseunicorns/uds-package-dubbd/pull/517)
