### ISSUE TITLE
Allow variable `type: file` in uds bundles

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/uds-cli#417]
### Is your feature request related to a problem? Please describe

It would be nice to have the ability to pass files as variables with uds bundles (ex. cert/key files)

### Describe the solution you'd like

- If I want to override the default tls.crt/tls.key for an ingress-gateway
- I could set the TLS.CRT variable to point to a file
- and the cert/key file would get added to the ingress-gateway deployment 

### Describe alternatives you've considered

(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by benmountjoy111** [comment]
HCND would also like this feature

**Comment by UncleGedd** [comment]
This is an oldie! I'm assuming still relevant though?

**Comment by benmountjoy111** [comment]
I would say yes. We would like a way to specify files like we could with zarf (for keys/certs, as Rex is also wanting to do)

**Comment by UncleGedd** [comment]
awesome, we'll prioritize this one; you should see it in the next couple of releases

**Comment by TristanHoladay** [comment]
@benmountjoy111 @brianrexrode just wanted to confirm that the priority for this is to work with variables (either setting zarf vars or helm override vars) not values in helm overrides. Is that correct?

**Comment by benmountjoy111** [comment]
correct. Want to be able to set uds/zarf vars to a file (particularly for certs/keys).

**Comment by TristanHoladay** [comment]
@benmountjoy111 @brianrexrode do y'all base64 encode your certs/keys yourselves or do you rely on something like SOPS? Just want to make sure we emulate the process people are used to.

**Comment by benmountjoy111** [comment]
our intent (tho we are not there yet) is to use SOPS so that we can check in our certs/keys encrypted. Right now we use github secrets and echo them to disk in our workflows (not the greatest solution). But i think handling the encryption/decryption of the files would be outside of this issue (i.e., we'd have to handle that, and once it's unencrypted, we could tell uds-cli to use it). Just my 2 cents tho

**Comment by TristanHoladay** [comment]
cool. kinda figured y'all would be ok doing all that before passing things on to cli, but wanted to make sure we weren't going to create a negative user experience if the expectation was for us to handle those kinds of things.
