### ISSUE TITLE
Enable the ability to run vendored zarf aliased to z

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#419]
### Is your feature request related to a problem? Please describe

I dont like typing. Sub-commands in zarf and uds get aliased to their first letter, for example `zarf p c` (package create). Now that zarf is vendored into uds I think we should extend my ability to be lazy with typing such that i can run `uds z p c`, rather than having to run `uds zarf p c`.

### Describe the solution you'd like

See above

### Describe alternatives you've considered

creating local aliases but i'd rather not 

### Additional context

N/A

**Comment by UncleGedd** [comment]
closed with #424
