### ISSUE TITLE
runtime error: slice bounds out of range when running `uds remove core --confirm`

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-cli#434]
### Environment

Device and OS: M2 Max, 14.2.1
App version: 0.9.0
Kubernetes distro being used: k3d (uds-k3d 0.3.1)
Other: `uds zarf package list`
```
     Package | Version | Components
     uds-k3d | 0.3.1   | [destroy-cluster create-cluster uds-dev-stack]
     init    | v0.32.2 | [zarf-injector zarf-seed-registry zarf-registry zarf-agent]
     core    | 0.12.0 | [prometheus-operator-crds istio-controlplane istio-admin-gateway istio-tenant-gateway istio-passthrough-gateway pepr-uds-core metrics-server neuvector loki kube-prometheus-stack promtail grafana]
```
docker desktop: 4.26.1 (131620)

### Steps to reproduce

1. `uds deploy k3d-core-demo:0.12.0`
2.  `uds zarf tools list`
3. See a package called `core` that I want to remove
4. `uds remove core --confirm`
5. Error
```
panic: runtime error: slice bounds out of range [:6] with length 4

goroutine 1 [running]:
github.com/defenseunicorns/uds-cli/src/pkg/utils.EnsureOCIPrefix(...)
        /home/runner/work/uds-cli/uds-cli/src/pkg/utils/oci.go:250
github.com/defenseunicorns/uds-cli/src/pkg/bundle.getOCIValidatedSource({0x16bbb2ea8, 0x4})
        /home/runner/work/uds-cli/uds-cli/src/pkg/bundle/remote.go:263 +0x420
github.com/defenseunicorns/uds-cli/src/pkg/bundle.CheckOCISourcePath({0x16bbb2ea8, 0x4})
        /home/runner/work/uds-cli/uds-cli/src/pkg/bundle/remote.go:330 +0x40
github.com/defenseunicorns/uds-cli/src/pkg/bundle.(*Bundle).Remove(0x140017a6000)
        /home/runner/work/uds-cli/uds-cli/src/pkg/bundle/remove.go:28 +0x38
github.com/defenseunicorns/uds-cli/src/cmd.glob..func13(0x10b9b9d40?, {0x140003f3aa0?, 0x4?, 0x10754ba68?})
        /home/runner/work/uds-cli/uds-cli/src/cmd/uds.go:129 +0x158
github.com/spf13/cobra.(*Command).execute(0x10b9b9d40, {0x140003f3a40, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x10b9ba8c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/defenseunicorns/uds-cli/src/cmd.Execute()
        /home/runner/work/uds-cli/uds-cli/src/cmd/root.go:60 +0x24
main.main()
        /home/runner/work/uds-cli/uds-cli/main.go:10 +0x1c
```

### Expected result

Package named `core` is removed or a sensible error is provided.

### Actual Result

non-sensible error. what is confusing code stack trace?

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/defenseunicorns/uds-cli/assets/46836330/3cf282db-8737-44ed-a09a-52d95a2c9808)

### Severity/Priority

medium-high?

### Additional Context

log file only had two lines "saving log file to..."

**Comment by decleaver** [comment]
hey @andrewg-xyz , so the `remove` command attempts to remove a bundle (and all of the packages in that bundle). To only [remove](https://github.com/defenseunicorns/uds-cli?tab=readme-ov-file#bundle-remove) a specific package, you can do `uds remove <bundle file> -p <package name>. 

Idk, i think from the logs its pretty clear what the problem is..... lol jk, we do need to clean that up and provide something helpful.

**Comment by andrewg-xyz** [comment]
Copy that. Might be good to have a `uds list` type command similar to `zarf package list` :)

**Comment by decleaver** [comment]
created a new [issue](https://github.com/defenseunicorns/uds-cli/issues/435) for us to provide some helpful messaging
