### ISSUE TITLE
Implement Checksum Validation for Downloaded Layers in RemoteBundle

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-cli#437]
### Environment

**Device and OS:** N/A (Development Environment)  
**App version:** [Specify the version of your application or tool where the issue was found]  
**Kubernetes distro being used:** N/A  
**Other:** N/A  

### Steps to reproduce

1. Invoke the [downloadPkgFromRemoteBundle](https://github.com/defenseunicorns/uds-cli/blob/823ac5e0461653b1ba69161af0a7784f000cf25f/src/pkg/sources/remote.go#L148) function in `src/pkg/sources/remote.go` to download a package from a remote bundle.

### Expected result

Each downloaded layer's integrity is verified through checksum validation, ensuring that the data has not been tampered with or corrupted during transmission.

### Actual Result

The [downloadPkgFromRemoteBundle](https://github.com/defenseunicorns/uds-cli/blob/823ac5e0461653b1ba69161af0a7784f000cf25f/src/pkg/sources/remote.go#L148) function currently does not perform checksum validation for downloaded layers, potentially allowing tampered or corrupted layers to be processed without detection.

### Visual Proof (screenshots, videos, text, etc)

N/A (This issue pertains to a missing security feature in the codebase, which does not lend itself easily to visual proof.)

### Additional Context

The proposed solution involves:
1. Obtaining the expected checksums for each layer, ideally provided alongside the layer metadata.
2. Calculate the downloaded layer's checksum using a secure hash algorithm (e.g., SHA-256).
3. Comparing the calculated checksum against the expected value and handling any discrepancies (e.g., logging an error, retrying the download, or failing the operation).

Implementing this feature will align the project with the best data integrity and security practices, significantly enhancing the package downloading process's reliability.

**Comment by UncleGedd** [comment]
Thanks for this issue and write up @naveensrinivasan ! I want to make sure I'm fully understanding; it looks like we do validate the checksums [here](https://github.com/defenseunicorns/uds-cli/blob/823ac5e0461653b1ba69161af0a7784f000cf25f/src/pkg/sources/remote.go#L54) after calling `downloadPkgFromRemoteBundle`. 

Noting that `ValidatePackageIntegrity` is a fn we use [from Zarf](https://github.com/defenseunicorns/zarf/blob/07541a61dc3b19452cdecd3bf800788cdc78e67a/src/pkg/packager/sources/validate.go#L62)

Does this implement your expected result?

**Comment by naveensrinivasan** [comment]
> Thanks for this issue and write up @naveensrinivasan ! I want to make sure I'm fully understanding; it looks like we do validate the checksums [here](https://github.com/defenseunicorns/uds-cli/blob/823ac5e0461653b1ba69161af0a7784f000cf25f/src/pkg/sources/remote.go#L54) after calling `downloadPkgFromRemoteBundle`.
> 
> Noting that `ValidatePackageIntegrity` is a fn we use [from Zarf](https://github.com/defenseunicorns/zarf/blob/07541a61dc3b19452cdecd3bf800788cdc78e67a/src/pkg/packager/sources/validate.go#L62)
> 
> Does this implement your expected result?

Thanks. You are right. It does take care of that.
