### ISSUE TITLE
Review and Secure Curl Usage in GitHub Actions Workflow

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-cli#445]
In our GitHub Actions workflow defined in .github/actions/install-tools/action.yaml, we have a step that uses curl to download and execute a script from the internet:
https://github.com/defenseunicorns/uds-cli/blob/ef4b57782f6db38afbf74d735aaa294bc59ab973/.github/actions/install-tools/action.yaml#L11
This software installation method raises potential security concerns, as it directly executes a script fetched from the internet. While this approach is commonly used, it can expose our CI/CD pipeline to risks if the remote content is compromised or there is a man-in-the-middle attack.
### Potential Risks
- Remote Execution Vulnerability: If the repository or the specific commit referenced is compromised, malicious code could be executed in our pipeline environment.
- Man-in-the-Middle (MitM) Attacks: Without verifying the integrity of the script before execution, there's a risk that the content could be altered in transit.

https://about.codecov.io/security-update/

**Comment by catsby** [comment]
Closed with #961
