### ISSUE TITLE
Set up gosec as part of the linter

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#448]
Set up `gosec` as part of [golangci-lint](https://golangci-lint.run/usage/linters/#gosec). Ensure this gets run as part of the `precommit` and in our workflows

**Comment by naveensrinivasan** [comment]
Yes, But it should be part of the CI.

**Comment by TristanHoladay** [comment]
i believe this is now running in our pre-commit hook when it calls golangci with our [.golangci.yml](https://github.com/defenseunicorns/uds-cli/blob/a74a65d9dc7fce24fcfd6e2f5a468a5a9fb52f9f/.golangci.yml#L25). And then that is run in CI in the [`scan-lint.yaml`](https://github.com/defenseunicorns/uds-cli/blob/a74a65d9dc7fce24fcfd6e2f5a468a5a9fb52f9f/.github/workflows/scan-lint.yaml#L23)

**Comment by UncleGedd** [comment]
> i believe this is now running in our pre-commit hook when it calls golangci with our [.golangci.yml](https://github.com/defenseunicorns/uds-cli/blob/a74a65d9dc7fce24fcfd6e2f5a468a5a9fb52f9f/.golangci.yml#L25). And then that is run in CI in the [`scan-lint.yaml`](https://github.com/defenseunicorns/uds-cli/blob/a74a65d9dc7fce24fcfd6e2f5a468a5a9fb52f9f/.github/workflows/scan-lint.yaml#L23)

LGTM
