### ISSUE TITLE
readme updates add uds context

### ISSUE THREAD

**Issue by gscallon** [defenseunicorns/uds-cli#452]
### Is your feature request related to a problem? Please describe

The README should contain links/information on how to find out more about UDS and the UDS ecosystem. This will allow those who end up on this project repo page to receive the necessary context about the tool they have stumbled upon.

The README should also provide some sort of definition of "what is this software" near the top of the README. A concise statement that describes what uds-cli is and what it can do will be helpful for those who are unfamiliar with UDS and/or uds-cli specifically.

### Describe the solution you'd like

- **Given** uds-cli exists alongside uds core, uds packages, etc
- **When** I read the uds-cli readme
- **Then** I am able to understand what UDS is at a high level, what uds-cli is and does, and I am able to access more information about all things UDS

### Describe alternatives you've considered

N/A

### Additional context

Approaching this as someone who has some prior experience working with uds-cli.

**Comment by decleaver** [comment]
We've updated our docs recently and link to them from the [readme](https://github.com/defenseunicorns/uds-cli?tab=readme-ov-file#official-documentation). The docs site also contains a UDS overview and documentation on UDS Core, mission capabilities,  and bundles.
