### ISSUE TITLE
Tab completion no longer works for tasks

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#493]
### Environment

Device and OS: ubuntu 22
App version: 0.9.3

### Steps to reproduce

1. Download latest uds
2. write bash completion to correct file
3. create tasks file with tasks
4. write `uds run` and hit tab

### Expected result

List of tasks is printed or tabbed through

### Actual Result

No tab completion results are given

**Comment by decleaver** [comment]
related to: https://github.com/defenseunicorns/uds-cli/pull/382

**Comment by UncleGedd** [comment]
fixed with https://github.com/defenseunicorns/uds-cli/pull/502
