### ISSUE TITLE
Debug output doesn't show in log file

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-cli#516]
### Environment

Device and OS: System76 darp8, popOS 22.04
App version: v0.9.4
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce

1. Run a uds command that uses Zarf as a library and normally would have debug output in the log

### Expected result

Debug logs are logged

### Actual Result

Debug logs are skipped

### Visual Proof (screenshots, videos, text, etc)

Current:
![image](https://github.com/defenseunicorns/uds-cli/assets/3977569/28c0ad98-b882-4b85-8f60-99bb65b01830)

Expected:
![image](https://github.com/defenseunicorns/uds-cli/assets/3977569/9a34933d-4b0e-4482-8697-486dbe821cf3)

### Severity/Priority

Medium - there are known work arounds but it does cost time in rerunning workflows / deployments when debug information is not readily available.

### Additional Context

This is more of an *ility that should be considered / checked for during the implementation of the logging fixes from https://github.com/defenseunicorns/zarf/pull/2380 - I wanted to document this as a bug since it is currently impacting us on UDS SWF.

**Comment by UncleGedd** [comment]
completed in https://github.com/defenseunicorns/uds-cli/pull/509
