### ISSUE TITLE
Improve bubble tea for CI use cases and to respect `--no-progress`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-cli#529]
### Is your feature request related to a problem? Please describe

**As** Ezra **I want** bubble tea to respect `--no-progress` **so that** I can cleanly use it in CI 

### Describe the solution you'd like

- **Given** I have something a core uds CLI command can operate on
- **When** I run `uds (create|deploy|publish) <thing> --no-progress`
- **Then** `uds-cli` respects that and disables spinners and animations while still showing useful output

### Describe alternatives you've considered

I realize `--no-tea` exists to fallback to `pterm` output but this is not ideal either because the landmarks within the output largely come from Zarf without clear demarks between things `uds-cli` is doing.  This can make it hard, for example, to distinguish two workflows that are largely the same (and can be easily mixed up) like the `Test`s in:

https://github.com/defenseunicorns/uds-common/actions/runs/8456524580/job/23166490067?pr=91
https://github.com/defenseunicorns/uds-common/actions/runs/8456524580/job/23166490447?pr=91

Having a solid CI-run output from the `--no-progress` flag that people already are using would make things much cleaner.

### Additional context

For now though we will likely fall back to `--no-tea` since that is cleaner and provides more useful output that is easier to traverse in CI.

**Comment by UncleGedd** [comment]
Thanks for this! What would you think of having a single flag `--ci` (or something like that) that is explicitly for use in CI? That way Ezra doesn't have to guess which flag should be used

**Comment by Racer159** [comment]
that could potentially work - ideally it would be a single thing that wouldn't change much as uds-cli evolves (since if it changes it cascades into the automation for multiple repos).

**Comment by mjnagel** [comment]
If you want to be a bit more heavy-handed and force people down a certain route for CI use cases you could switch automatically based on the `CI` environment variable (similar to how zarf does https://github.com/defenseunicorns/zarf/blob/08c92e12a4a2b05d0ea5abe055c7c01ba9964051/src/cmd/common/setup.go#L48-L51).

**Comment by UncleGedd** [comment]
This is the worst:
![Screenshot 2024-04-15 at 3 34 06 PM](https://github.com/defenseunicorns/uds-cli/assets/42304551/b3f97508-b5eb-4f67-a007-f3e29234c6e3)

**Comment by mjnagel** [comment]
@UncleGedd if it helps - my experience so far is that adding `--no-progress` to your `uds run` command that triggers the task seems to eliminate a lot of the progress fluff like that screenshot. Not confident its a perfect solve for this issue, but definitely have seen the case where `maru` seems to be the cause of the progress bars, so passing `no-progress` there seems to resolve a lot of them. I believe when the runner code was in uds-cli it auto-detected `CI` environments and handled that seamlessly. Is that missing from `maru` OR just not getting passed from cli -> maru?

**Comment by zachariahmiller** [comment]
Just in case anyone needs something in the meantime rather than adding --no-tea all over you can do `UDS_NO_TEA=true uds deploy bundle:version` or `export UDS_NO_TEA=true` for embedded in `uds run`/ to disable all around.

**Comment by UncleGedd** [comment]
> I believe when the runner code was in uds-cli it auto-detected CI environments and handled that seamlessly

I don't think we ever actually implemented this, @decleaver ?

**Comment by UncleGedd** [comment]
The ideal state is that users can run `./uds deploy` in a task with no flags (or perhaps just `--no-progress`) and the output looks good in CI, but to do this UDS CLI needs to either pass hidden flags into `./uds` commands or have some other mechanism of knowing that it's being called from a task. This is currently blocked by: https://github.com/defenseunicorns/maru-runner/issues/78

**Comment by Madeline-UX** [comment]
I vote to align command to --no-progress unless there is a similar command in K8 or Kubectl

**Comment by UncleGedd** [comment]
Revisiting this issue now that BubbleTea is ☠ . When running `./uds ... --no-progress` inside a task everything should look okay in CI. @mjnagel @Racer159 could you guys confirm this?

Also, if you like we can automatically set `--no-progress` on all `./uds` commands in tasks without the user having to specify that flag in the task itself. In other words:
```yaml
...
- cmd: ./uds create . --confirm # no need to set --no-progress when running inside a task
```

**Comment by Arsinic** [comment]
Would this `--no-progress` or CI environment mode also add support for the `--no-color` flag available in Zarf?

I ask because in CI currently trying to use UDS CLI out passed to standard error to do more CI things and in zarf using `--no-color` makes this pretty trivial, but in uds-cli I need to remove color ascii chars.

**Comment by UncleGedd** [comment]
@Arsinic just realized this is a problem with that `--list-images` flag, we have a change that'll be out in the next UDS CLI release (later this week) that ensures that output goes `stdout` and is machine readable.

Beside `uds inspect --list-images` are there any other commands whose output you want to ingest with other tooling?

 For your original question, yes! Great callout, I forgot about `--no-color`
