### ISSUE TITLE
Order of Removing Deployed Bundle Packages

### ISSUE THREAD

**Issue by UnicornChance** [defenseunicorns/uds-cli#53]
Problem: When bundling and deploying multiple packages they are deployed in the order they are defined in `uds-bundle.yaml`. However when removing the bundle using `uds bundle remove <bundle>.tar.zst --confirm` also removes those packages in the same order, rather than in a first in last out order.

**Comment by UncleGedd** [comment]
Fixed with https://github.com/defenseunicorns/uds-cli/pull/56
