### ISSUE TITLE
Support `--retries` on deploy operations

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-cli#531]
### Is your feature request related to a problem? Please describe

As Ezra I want to be able to specify Helm and image retries so that I can have a more robust deploy process.

### Describe the solution you'd like

- **Given** I have a UDS bundle with large images
- **When** I run `uds deploy <bundle> --retries <x>`
- **Then** `uds-cli` passes that along to Zarf's package options
- **And When** an image push error or Helm error occurs
- **Then** the deployment respects that value

### Describe alternatives you've considered

This is currently a feature of Zarf, `uds-cli` could implement their own version but the easiest path for now is to reuse the same logic.

### Additional context

This should be relatively simple to wire in, requiring a new command flag:
https://github.com/defenseunicorns/uds-cli/blob/0d030d46b2e5440ecf0e382b25312aef731792eb/src/cmd/uds.go#L291
wired to package options (which has retries in it):
https://github.com/defenseunicorns/uds-cli/blob/main/src/pkg/bundle/deploy.go#L123

**Comment by eddiezane** [comment]
ref: https://github.com/defenseunicorns/zarf/pull/2345
