### ISSUE TITLE
Support scrolling in the TUI

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-cli#553]
### Overview
Currently when viewing a deployment through the TUI(?), you can expand a view of the logs by pressing `l` as shown below:
![image](https://github.com/defenseunicorns/uds-cli/assets/9499393/a3705e79-4047-44d6-959d-cd219cc2cde2)

The output can scroll quite quickly, and occasionally it would be useful to review output by scrolling up (rather than waiting for a deploy to finish and using `uds logs`).

### Proposed solution
Enable scrolling in the log preview.

**Comment by UncleGedd** [comment]
Closing bc we nixed the TUI: https://github.com/defenseunicorns/uds-cli/blob/main/adr/0004-tui.md
