### ISSUE TITLE
engine: UDS state and intelligent removes

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#614]
### Is your feature request related to a problem? Please describe

Intelligent package handling on bundle upgrades

### Describe the solution you'd like

- **Given** a bundle has been deployed successfully once, and now I'm upgrading
- **When** I upgrade and a package has been removed from the `uds-bundle.yaml`
- **Then** I want the option to remove the removed package from my cluster

### Additional context

- Creating this issue based on a Slack thread with @mjnagel and @YrrepNoj 
- State was implemented in https://github.com/defenseunicorns/uds-cli/pull/868

**Comment by mjnagel** [comment]
I suspect the first part of this is likely keeping track of bundles in a secret (similar to how zarf stores package state in a secret)? If the "bundle state secret" keeps track of zarf packages (at a minimum) then on an "upgrade" we would know which packages were removed/added. I think there's probably another layer that zarf might need to handle (component removals) but handling bundle state is a good first thing to tackle.

**Comment by MxNxPx** [comment]
@UncleGedd we definitely have hit this problem with `uds-infrastructure` and would benefit from solving.
we needed to remove a zarf package that was defined in a bundle (example: a LFAI model gets swapped out), and ended up manually connecting to the cluster and doing a `zarf package remove`.

**Comment by UncleGedd** [comment]
@decleaver is working on a design doc for this feature over in https://github.com/defenseunicorns/uds-cli/pull/834

**Comment by UncleGedd** [comment]
Need to figure out vision for UDS state with @jeff-mccoy

**Comment by UncleGedd** [comment]
Spoke with Jeff and agreed to implement a minimal version of UDS state

**Comment by catsby** [comment]
Update: we're evaluating options here, so I'm going to close this issue at this time.
