### ISSUE TITLE
Spike: What colors can be used in tasks

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-cli#630]
## Test

Observe task runner deploying UDS Bundle - to determine what colors are shown. 

Please attach video recording of the test.

**Comment by UncleGedd** [comment]
What do the following look like within a task?
- Colors (16 ANSI colors)?
- Bold?
- Emojis?
- Lines
- Rows?
- Collums?
- Scroll?
- Ascii art (box drawing characters)
- Error messages

**Comment by UncleGedd** [comment]
Also, run `kubectl` in a task and see what its output looks like, does it look normal?

**Comment by TristanHoladay** [comment]
video of current colors when running deploy via task:

[Screencast from 06-05-2024 10:44:16 AM.webm](https://github.com/defenseunicorns/uds-cli/assets/40547442/756846cc-1cfb-4538-951e-906813c69b1b)

**Comment by TristanHoladay** [comment]
looks like styles applied to text output is being overwritten (?) by maru-runner. the styles show up not when used in a uds task. Interestingly, styles for padding, border, etc... carry over.

Not in task:
![Screenshot from 2024-06-06 14-25-30](https://github.com/defenseunicorns/uds-cli/assets/40547442/76e0b9c4-6ed7-41d4-aba0-df124698aa44)

In task:
![Screenshot from 2024-06-06 14-24-07](https://github.com/defenseunicorns/uds-cli/assets/40547442/a7303565-bfa1-40c6-b347-9825ebb5cb43)

**Comment by UncleGedd** [comment]
Verified with @Madeline-UX that these docs are sufficient

**Comment by Madeline-UX** [comment]
@TristanHoladay This is great. i agree we should pass this along to the maru team as feedback.
