### ISSUE TITLE
Refactor overrides

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#654]
### Describe what should be investigated or refactored

- Currently, we handle all of our bundle overrides over in [deploy.go](https://github.com/defenseunicorns/uds-cli/blob/main/src/pkg/bundle/deploy.go). Let's look into refactoring all of this logic into its own package in the `pkg` dir
- Need to also clean up the code in overrides, a code smell is the large number of args in `addOverride`. Explore how to reduce the number of args in that fn and clean up the logic

**Comment by TristanHoladay** [comment]
@UncleGedd do you want to keep this open or close given the recent changes we've made?

**Comment by UncleGedd** [comment]
👍 we can close this one
