### ISSUE TITLE
Add ability to view override and config options for a given bundle prior to deployment

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-cli#655]
### Is your feature request related to a problem? Please describe

As a bundle creator i would like to be able to have the consumer of my bundle be able to ascertain the specific configuration options they have available to them. While this could totally be readme documentations it would be nice for it to be something self-contained to the bundle definition and uds cli as they might be deploying the bundle in an environment without network access. Currently all configuration options, zarf vars, helm overrides, etc are available to the uds-cli as uds vars when reading in the bundle. As such i think it makes sense to have some command in uds-cli to point to a bundle and be able to have the CLI output the given configuration options available to the bundle deployer.

**Comment by TristanHoladay** [comment]
There's currently `uds inspect` and the pre-deploy view when deploying a bundle that shows some of this info, but not all and not in a great format for user experience. 

@Madeline-UX is tracking this with us now and we're thinking this potentially is not only a "show me what i can configure" feature but also a "let me check my configuration" feature to make sure things are set the way you expected (similar to `helm template`). So the 3 questions we're seeking to answer from a user's view are:

1) What overrides are possible / what has been overridden?
2) What is the value that will be deployed (by default or if the user changes)?
3) What is the source of that value (eg. config, cli, env vars, defaults in the bundle yaml)

**Comment by Madeline-UX** [comment]
Ideating through this design sketch - to help better indicate what variable values are being overridden and the source of those overrides. 
![IMG_7338](https://github.com/defenseunicorns/uds-cli/assets/92826525/c90f657c-1238-4bdd-81ee-7d0d262f34f3)

**Comment by TristanHoladay** [comment]
Notes from discussions with @Madeline-UX and @zachariahmiller:

There is a desire to see all possible configurations (bundle helm overrides, zarf vars, zarf helm overrides), but there are issues with showing everything in terms of user experience (could overload users, could show a lot of stuff they don't care about). And the pre-deploy view, while a good update, doesn't necessarily help when most users are probably not stopping to read through that output before actually deploying. It could be more helpful to have a separate command as well for getting this info.

So next steps look like:

1. keep pre-deploy view changes, except remove color coding for now.

1. Mads is going to talk with some Delivery people to understand their process and what's beneficial to them.

1. potentially modify `uds inspect` to output bundle overrides and maybe a flag or some other mechanism for opting for showing all zarf package variables as well.

**Comment by UncleGedd** [comment]
closed with https://github.com/defenseunicorns/uds-cli/pull/674
