### ISSUE TITLE
Set UDS Bundle version during bundle create

### ISSUE THREAD

**Issue by cbrech** [defenseunicorns/uds-cli#726]
### Is your feature request related to a problem? Please describe

As a human who messes up manual versioning, I would like to use Gitlab CI runners to set the bundle version during the build process. On Zarf in our zarf.yaml we use a variable for the version number and set it via the --set feature on zarf package create. This allows us to deterministically know the zarf package file name after creation and the ref that will be available once we publish the image while allowing us to use the same pipeline across multiple projects.

### Describe the solution you'd like

- **Given** an updated uds-bundle.yaml
- **When** is making its way through our build pipeline
- **Then** The version is set by CI

### Describe alternatives you've considered
Any other way to use Gitlab runners to help manage the versioning of our packages.

### Additional context
N/A

**Comment by UncleGedd** [comment]
Appreciate the issue @cbrech ! Just to clarify, are you wanted to set the bundle version or a package's ref?

**Comment by cbrech** [comment]
The bundle itself's version. Perhaps the name too.

**Comment by UncleGedd** [comment]
👍 we can do that, we'll prioritize this in the next couple of releases
