### ISSUE TITLE
test-bundle pipeline step is too slow

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#741]
### Describe what should be investigated or refactored

The `test-bundle` portion of the pipeline which runs `bundle_test.go` takes ~10 minutes to complete. See how we can move tests out of this massive file and/or refactor into more integration/unit style testing. Goal should be <5 minutes for this job

![Screenshot 2024-06-28 at 10 52 34 AM](https://github.com/defenseunicorns/uds-cli/assets/42304551/03e11ab5-2846-48a4-a79c-a7f604182040)

**Comment by TristanHoladay** [comment]
![Screenshot from 2024-08-19 08-48-48](https://github.com/user-attachments/assets/e29ad638-597d-4c32-af1d-9cb18895b006)

**Comment by UncleGedd** [comment]
thanks @TristanHoladay great steps in the right direction
