### ISSUE TITLE
Fix help docs for dev deploy

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#755]
### Description
```
❯ uds dev deploy --help
[beta] Creates and deploys a UDS bundle from a given directory in dev mode, setting package options like YOLO mode for faster iteration.
```

^ needs to be updated!

Ensure `dev deploy` help docs indicate that this feature works on both remote and local bundles

**Comment by mjnagel** [comment]
Maybe connected here I noticed the usage was not super clear:
```
❯ uds dev deploy --help
[beta] Creates and deploys a UDS bundle from a given directory in dev mode, setting package options like YOLO mode for faster iteration.

Usage:
  uds dev deploy [flags]
  ```

I assume I need to pass in more than just `[flags]`? Probably a local or OCI reference is also required?

**Comment by UncleGedd** [comment]
> I assume I need to pass in more than just [flags]? Probably a local or OCI reference is also required?

Good callout, yes indeed. Either a path to a folder containing a `uds-bundle.yaml` or an OCI url (not `oci://` isn't required)
