### ISSUE TITLE
Shortcuts for `uds run --list` and `uds run --list-all`

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-cli#776]
```
uds run --list-all
```

is a lot to type when I'm doing it 10,000 times a day.

Could we possibly get `uds run -l` which would be equivalent to `uds run --list` and `uds run -L `which would be equivalent to `uds run --list-all`?

**Comment by UncleGedd** [comment]
Thanks @RothAndrew ! Closing this issue in UDS CLI as it'll be implemented in Maru https://github.com/defenseunicorns/maru-runner/pull/125
