### ISSUE TITLE
Setup a Github Action to install UDS CLI

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#847]
### Describe what should be investigated or refactored

Setup a Github Action to install UDS CLI

**Comment by catsby** [comment]
It seems we have an action already, or do you mean something else like an action to compile uds-cli from the current code?

- https://github.com/defenseunicorns/uds-cli/blob/main/.github/actions/install-uds-cli/action.yaml

**Comment by UncleGedd** [comment]
Published action for others to use. If the link above can be used by others, then let's provide some docs for it

**Comment by catsby** [comment]
I suppose it can be used, but I would rather people reach in to a common repo that provides shared actions than directly in to this one. Otherwise we can setup an independent action like https://github.com/defenseunicorns/setup-zarf

**Comment by catsby** [comment]
See also #483

**Comment by zachariahmiller** [comment]
I'm going to create a repo for this action that mirrors the [setup-zarf](https://github.com/defenseunicorns/setup-zarf/tree/main) action named setup-uds

**Comment by catsby** [comment]
https://github.com/defenseunicorns/setup-uds is out there, thank you @zachariahmiller !
