### ISSUE TITLE
Protected variable 'VERSION'

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/uds-cli#860]
### Environment

Device and OS: linux amd64 ubuntu
App version: v0.14.1
Kubernetes distro being used: n/a
Other: n/a

### Steps to reproduce

create a `test.yaml` file with the follow content:
```yaml
variables:
  - name: VERSION
    default: "v1.30.3-k3s1"
  
tasks:
  - name: test-uds-version
    description: "version"
    actions:
      - description: "version"
        cmd: echo ${VERSION}
```

Execute `uds run -f test.yaml test-uds-version`

### Expected result

```bash
 NOTE  Saving log file to /tmp/zarf-2024-08-16-22-16-50-3475898727.log

  •  Saving log file to /tmp/maru-2024-08-16-22-16-50-657926013.log
     v1.30.3-k3s1                                                                                                                                       
  ✔  Completed "version" 
```

### Actual Result

```
 NOTE  Saving log file to /tmp/zarf-2024-08-16-22-16-50-3475898727.log

  •  Saving log file to /tmp/maru-2024-08-16-22-16-50-657926013.log
     v0.14.0                                                                                                                                          
  ✔  Completed "version" 
```

### Severity/Priority
Low
### Additional Context

Adding the question label in the event that `VERSION` is indeed a protected variable and this is expected

**Comment by UncleGedd** [comment]
Appreciate the issue! We'll take a look into this and https://github.com/defenseunicorns/uds-cli/issues/861. If `VERSION` is indeed protected we'll be sure to call it out in our docs

**Comment by catsby** [comment]
Hey @brandtkeller ! Are you still able to reproduce this? I tried on `main` as well as `v0.14.0` and `v0.14.1` and wasn't able to. 

```zsh
 ~/Desktop
 ➜ cat test.yaml
variables:
  - name: VERSION
    default: "v1.30.3-k3s1"

tasks:
  - name: test-uds-version
    description: "version"
    actions:
      - description: "version"
        cmd: echo ${VERSION}%

 ~/Desktop
 ➜ uds version

 NOTE  Using config file
v0.14.1

 ~/Desktop
 ➜ uds run -f test.yaml test-uds-version

 NOTE  Saving log file to
       /var/folders/lk/181f8tjj7xg0c368tfmw35kr0000gn/T/zarf-2024-09-19-15-51-19-3527828344.log

  •  Saving log file to
       /var/folders/lk/181f8tjj7xg0c368tfmw35kr0000gn/T/maru-2024-09-19-15-51-19-2978173952.log
     v1.30.3-k3s1
  ✔  Completed "version"
```

**Comment by brandtkeller** [comment]
I just realized that this problem stems from my use of an `env` variable in my dev-container where I specify `UDS_VERSION` as the version of the tool to download - and as such the [viper config](https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/viper.go#L80) is picking up on that and setting all downstream instances of `VERSION` by default. 

No action required.

**Comment by catsby** [comment]
@brandtkeller glad you got that sorted, thanks for the update
