### ISSUE TITLE
Viper config file identification

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/uds-cli#861]
Looking at the viper configuration - I believe it is expected that uds identifies when a config file is not present for logging purposes - IE see warning [here](https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/viper.go#L88) and [here](https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/viper.go#L98)

based on [this conditional](https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/viper.go#L87) - the warning will never be executed as you want to be checking for `ok` instead of `!ok`. 

This is duplicated in the [following function](https://github.com/defenseunicorns/uds-cli/blob/main/src/cmd/viper.go#L93) - and when fixed I expect you would see multiple warning messages for a single command execution. Might be worth removing the additional check. 

### Steps to reproduce

1. Execute any uds command which can process viper configurations without having a valid uds-config file present in the expected locations

### Expected result

Warning when a config file was not identified

### Actual Result

no warning message

### Severity/Priority

Low

**Comment by brandtkeller** [comment]
Ah - I should read more. Comments indicate ignoring the errors on purpose. Thus those warnings would never be hit. 

I was trying to debug #860 and was getting a message "using config file" and had to do some tracing to understand that this was just missed. Can close this issue if intent is to not log config file not being found.

**Comment by catsby** [comment]
Hey @brandtkeller , me again - I believe we took care of that in https://github.com/defenseunicorns/uds-cli/issues/912 (by way of https://github.com/zarf-dev/zarf/pull/2985), so I'm going to close this now. Let me know if I've missed something!
