### ISSUE TITLE
printing extraneous information on `uds version`

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#912]
### Steps to reproduce

1. Run `uds version`

### Expected result

I just see the UDS version printed to the console

### Actual Result

![Screenshot 2024-09-06 at 4 03 45 PM](https://github.com/user-attachments/assets/c426e024-855d-4bde-b600-bbd84f72162e)

**Comment by catsby** [comment]
For what it's worth, this was introduced somewhere in [v0.14.1](https://github.com/defenseunicorns/uds-cli/releases/tag/v0.14.1)

**Comment by catsby** [comment]
I opened https://github.com/zarf-dev/zarf/pull/2985 to address this. If merged we can bump our Zarf dependency and resolve this

**Comment by catsby** [comment]
https://github.com/zarf-dev/zarf/pull/2985 was merged so this will resolve after Zarf's next release and we update. @UncleGedd in that case, should we close this now, or wait?

**Comment by UncleGedd** [comment]
IMO we should keep it open until we update Zarf and verify that everything works as expected

**Comment by UncleGedd** [comment]
Fixed!
