### ISSUE TITLE
Remove extra output from `uds run`

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#916]
### Describe what should be investigated or refactored

When running Maru tasks via `uds run`, remove the "Saving log file" notes

![Screenshot 2024-09-09 at 1 58 38 PM](https://github.com/user-attachments/assets/0327f849-ee16-4d3b-b9ed-8f305da657a2)

**Comment by catsby** [comment]
Unless I'm mistaken, maru-runner doesn't seem to allow silencing this `NOTE:` without completely disabling the logs entirely. 

- https://github.com/defenseunicorns/maru-runner/blob/535258256cd1714f55e643075ae15919316e4aec/src/cmd/root.go#L89-L93
- https://github.com/defenseunicorns/maru-runner/blob/535258256cd1714f55e643075ae15919316e4aec/src/pkg/utils/utils.go#L28-L39

We can remove this `NOTE:` here by completely turning off logging for Zarf and Maru-runner in `src/cmd/vendored.go`:

```diff
diff --git a/src/cmd/vendored.go b/src/cmd/vendored.go
index 47cf4d5..eda265a 100644
--- a/src/cmd/vendored.go
+++ b/src/cmd/vendored.go
@@ -26,6 +26,11 @@ var runnerCmd = &cobra.Command{
 	Use:     "run",
 	Aliases: []string{"r"},
 	Short:   lang.CmdRunShort,
+	PersistentPreRunE: func(cmd *cobra.Command, _ []string) error {
+		// disable Zarf log file
+		config.SkipLogFile = true
+		return nil
+	},
 	RunE: func(_ *cobra.Command, _ []string) error {
 		os.Args = os.Args[1:] // grab 'run' and onward from the CLI args
 
@@ -57,6 +62,9 @@ var runnerCmd = &cobra.Command{
 		}
 
 		runnerCLI.RootCmd().SetArgs(os.Args)
+		// disable maru-runner log file
+		runnerCLI.RootCmd().PersistentFlags().Set("no-log-file", "true")
+
 		runnerCLI.Execute()
 
 		return nil
```

but that turns off logging for them both entirely, as opposed to just silencing the message. Is that what we want?

**Comment by UncleGedd** [comment]
https://github.com/defenseunicorns/uds-cli/pull/919 removes the extra Zarf output, still need to address the Maru output

**Comment by catsby** [comment]
PR for this is here https://github.com/defenseunicorns/uds-cli/pull/925 but it depends on a Maru PR
