### ISSUE TITLE
`uds ui` tmp dir clean up and graceful exit

### ISSUE THREAD

**Issue by decleaver** [defenseunicorns/uds-cli#922]
### Describe what should be investigated or refactored

Investigate:
1. What happens when the user hits ctrl-c? Can we force a cleanup of the tmp dir?
2. Besides ctrl-c is there a graceful way to exit uds ui?

follow up issue based on PR https://github.com/defenseunicorns/uds-cli/pull/917

**Comment by UncleGedd** [comment]
fixed with https://github.com/defenseunicorns/uds-cli/pull/926
